blango/urls.py
from django.contrib import admin
import debug_toolbar
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import blango_auth.views
from django_registration.backends.activation.views import RegistrationView
from blango_auth.forms import BlangoRegistrationForm


import blog

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/profile/", blango_auth.views.profile, name="profile"),
    path("accounts/register/",RegistrationView.as_view(form_class=BlangoRegistrationForm), name="django_registration_register",),
    path('', include('blog.urls')),
    path("ip/", blog.views.get_ip),
    path("accounts/", include("django_registration.backends.activation.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

blog/urls.py
from django.urls import path, include
from . import views
app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path("post/<slug>/", views.post_detail, name="blog-post-detail"),
    path("accounts/", include("django.contrib.auth.urls")),
]

blango_auth/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from django.utils.translation import gettext_lazy as _


# Create your models here.
class BlangoUserManager(UserManager):
    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("Email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField(
        _("email address"),
        unique=True,
    )

    objects = BlangoUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

blog/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType

# Create your models here.
from django.conf import settings

class Tag(models.Model):
    value = models.TextField(max_length=100)

    def __str__(self):
        return self.value


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    modified_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(blank=True, null=True, db_index=True)
    title = models.TextField(max_length=100)
    slug = models.SlugField()
    summary = models.TextField(max_length=500)
    content = models.TextField()
    tags = models.ManyToManyField(Tag, related_name='posts')
    comments = GenericRelation('Comment')

    def __str__(self):
        return self.title


class Comment(models.Model):
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField(db_index=True)
    content_object = GenericForeignKey('content_type', 'object_id')
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    modified_at = models.DateTimeField(auto_now=True)


class AuthorProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="profile"
    )
    bio = models.TextField()

    def __str__(self):
        return f"{self.__class__.__name__} object for {self.user}"

blango_auth/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django_registration.forms import RegistrationForm

from blango_auth.models import User


class BlangoRegistrationForm(RegistrationForm):
    class Meta(RegistrationForm.Meta):
        model = User

    def __init__(self, *args, **kwargs):
        super(BlangoRegistrationForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit("submit", "Register"))

blog/forms.py
from .models import Comment
from django import forms
from crispy_forms.layout import Submit
from crispy_forms.helper import FormHelper


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit'))

blango_auth/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


@login_required
def profile(request):
    return render(request, "blango_auth/profile.html")

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.shortcuts import redirect
from blog.forms import CommentForm
import logging
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_headers


logger = logging.getLogger(__name__)

from .models import Post
# Create your views here.
def index(request):
  posts = (Post.objects.filter(published_at__lte=timezone.now())
  .select_related("author"))
  print('here')
  logger.warning('Got %d posts', len(posts))
  return render(request, 'blog/index.html', {
      'posts': posts
  })

def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)    
    logging.warning('Created comment on post %d wiht user %s', post.pk, request.user)
    if request.user.is_active:
        if request.method == "POST":
            comment_form = CommentForm(request.POST)

            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.content_object = post
                comment.creator = request.user
                comment.save()
                return redirect(request.path_info)
        else:
            comment_form = CommentForm()
    else:
        comment_form = None

    return render(request, "blog/post-detail.html", {
      "post": post,
      "comment_form": comment_form,
    })


def get_ip(request):
  from django.http import HttpResponse
  return HttpResponse(request.META['REMOTE_ADDR'])

blango_auth/templates/blango_auth/profile.html
{% extends "base.html" %}
{% load blog_extras %}
{% block title %}Blango Profile{% endblock %}
{% block content %}
{% row %}
    {% col %}
        <p>Logged in as {{ request.user }}.</p>
        <p><a href="{% url "logout" %}">Log Out</a></p>
    {% endcol %}
{% endrow %}
{% endblock content %}

blango_auth/templates/django_registration/activation_complete.html
{% extends "base.html" %}
{% load crispy_forms_tags blog_extras %}
{% block title %}Activation Complete{% endblock %}
{% block content %}
{% row "justify-content-center" %}
    {% col "col-md-6" %}
        <h2>Activation Complete</h2>
        <p>Your account is now activated! You can now log in and use Blango.</p>
        <p><a href="{% url "login" %}">Log In</a></p>
    {% endcol %}
{% endrow %}
{% endblock %}

blango_auth/templates/django_registration/activation_failed.html
{% extends "base.html" %}
{% load crispy_forms_tags blog_extras %}
{% block title %}Activation Failed{% endblock %}
{% block content %}
{% row "justify-content-center" %}
    {% col "col-md-6" %}
        <h2>Activation Failed</h2>
        <p>Sorry, we couldn't activate your account.</p>
        <p>{{ activation_error.message }}</p>
    {% endcol %}
{% endrow %}
{% endblock %}

blango_auth/templates/django_registration/registration_closed.html
{% extends "base.html" %}
{% load crispy_forms_tags blog_extras %}
{% block title %}Registration Closed{% endblock %}
{% block content %}
{% row "justify-content-center" %}
    {% col "col-md-6" %}
        <h2>Registration is currently closed</h2>
    {% endcol %}
{% endrow %}
{% endblock %}

blango_auth/templates/django_registration/registration_complete.html
{% extends "base.html" %}
{% load crispy_forms_tags blog_extras %}
{% block title %}Registration Successful{% endblock %}
{% block content %}
{% row "justify-content-center" %}
    {% col "col-md-6" %}
        <h2>Your registration was successful</h2>
        <p>Check your email to validate your account.</p>
    {% endcol %}
{% endrow %}
{% endblock %}

blango_auth/templates/django_registration/registration_form.html
{% extends "base.html" %}
{% load crispy_forms_tags blog_extras %}
{% block title %}Register for Blango{% endblock %}
{% block content %}
{% row "justify-content-center" %}
    {% col "col-md-6" %}
        <h2>Register for Blango</h2>
        {% crispy form %}
    {% endcol %}
{% endrow %}
{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}
{% block content %}
{% load blog_extras %}
  <h2>Blog Posts</h2>
  {% for post in posts %}
    {% row 'border-bottom' %}
    {% col %}
      <h3>{{ post.title }}</h3>
      {% include 'blog/post-byline.html' %}
      <p>{{ post.summary }}</p>
      <p>{{ post.content|wordcount }} words</p>
      <a href="{% url 'blog:blog-post-detail' post.slug %}">Read more</a>
    {% endcol %}
    {% endrow %}
  {% endfor %}

{% endblock %}

blog/templates/blog/post-byline.html
{% load blog_extras %}
<small>By {{ post.author|author_details:request.user }} on {{ post.published_at|date:"M, d Y" }}</small>
<!--<small>By {% author_details_tag %} on {{ post.published_at|date:"M, d Y" }}</small>-->

blog/templates/blog/post-comments.html
{% load blog_extras crispy_forms_tags %}
<h4>Comments</h4>
{% for comment in post.comments.all %}
{% row "border-top pt-2" %}
    {% col %}
        <h5>Posted by {{ comment.creator }} at {{ comment.created_at|date:"M, d Y h:i" }}</h5>
    {% endcol %}
{% endrow %}
{% row "border-bottom" %}
    {% col %}
        <p>{{ comment.content }}</p>
    {% endcol %}
{% endrow %}
{% empty %}
    {% row "border-top border-bottom" %}
        {% col %}
            <p>No comments.</p>
        {% endcol %}
    {% endrow %}
{% endfor %}
{% if request.user.is_active %}
{% row "mt-4" %}
    {% col %}
    {% crispy comment_form %}
    {% endcol %}
{% endrow %}
{% endif %}

blog/templates/blog/post-detail.html
{% extends "base.html" %}
{% block content %}
{% load blog_extras %}
{% load blog_extras cache %}

<h2>{{ post.title }}</h2>
<div class="row">
    <div class="col">
        {% include "blog/post-byline.html" %}
    </div>
</div>
{% row %}
    {% col %}
        {{ post.content|safe }}
    {% endcol %}
{% endrow %}
<!-- existing code here -->
{% if post.author.profile %}
    {% row %}
        {% col %}
            <h4>About the author</h4>
            <p>{{ post.author.profile.bio }}</p>
        {% endcol %}
    {% endrow %}
{% endif %}

{% include "blog/post-comments.html" %}

{% row %}
    {% col %}
        {% cache 3600 recent_posts %}
            {% recent_posts post %}
        {% endcache %}
    {% endcol %}
{% endrow %}

{% endblock %}

blog/templates/blog/post-list.html
<h4>{{ title }}</h4>
<ul>
{% for post in posts %}
    <li><a href="{% url "blog:blog-post-detail" post.slug %}">{{ post.title }}</a></li>
{% endfor %}
</ul>

templates/base.html
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  {% load static %}
  <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <title>{% block title %}Welcome to Blango{% endblock %}</title>

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Blango Home</a>
        <div class="d-flex">
            {% if request.user.is_active %}
                <a class="nav-link" href="{% url "profile" %}">Profile</a>
                <a class="nav-link" href="{% url "logout" %}">Log Out</a>
            {% else %}
                <a class="nav-link" href="{% url "django_registration_register" %}">Register</a>
                <a class="nav-link" href="{% url "login" %}">Log In</a>
            {% endif %}

        </div>
    </div>
</nav>


  {% block content %}


  {% endblock %}
</div>
<script src="{% static 'bootstrap.min.js' %}"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>